// @ts-check
import { icons as riCollection } from '@iconify-json/ri'

/**
 * @type {string[]}
 */
const riIconNames = [
  'account-circle-line',
  'add-line',
  'admin-line',
  'arrow-drop-left-line',
  'arrow-drop-right-line',
  'arrow-go-back-line',
  'arrow-left-double-line',
  'arrow-right-double-line',
  'arrow-right-line',
  'arrow-right-s-line',
  'award-line',
  'building-line',
  'checkbox-blank-circle-fill',
  'checkbox-circle-line',
  'clipboard-line',
  'close-line',
  'code-s-slash-line',
  'dashboard-line',
  'delete-bin-7-line',
  'exchange-line',
  'eye-line',
  'eye-off-line',
  'file-download-line',
  'file-info-line',
  'filter-line',
  'filter-off-line',
  'flow-chart',
  'focus-3-line',
  'folder-line',
  'folder-shield-2-line',
  'folders-line',
  'folder-user-line',
  'github-line',
  'git-merge-line',
  'git-repository-private-line',
  'global-line',
  'key-2-line',
  'loader-4-line',
  'lock-line',
  'lock-unlock-line',
  'mail-line',
  'moon-clear-line',
  'newspaper-line',
  'pencil-line',
  'question-line',
  'refresh-line',
  'restart-line',
  'send-plane-line',
  'server-line',
  'settings-3-line',
  'shapes-line',
  'shield-check-line',
  'sound-module-line',
  'stock-line',
  'sun-line',
  'team-line',
  'tools-line',
  'upload-cloud-line',
  'user-add-line',
  'user-shared-2-line',
]

/**
 * @type {[import('@iconify/vue').IconifyJSON, string[]][]}
 */
export const collectionsToFilter = [
  [riCollection, riIconNames],
]
