---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.project }}-app
  namespace: {{ .Values.argocd.namespace }}
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- .Values.commonLabels | toYaml | nindent 4 }}
spec:
  project: {{ .Values.argocd.project }}-app
  sources: {{ .Values.application.repositories | toYaml | nindent 4 }}
  destination:
    name: {{ .Values.application.destination.name }}
    namespace: {{ .Values.application.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
