apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- .Values.commonLabels | toYaml | nindent 4 }}
  name: {{ .Values.argocd.project }}-env
  namespace: {{ .Values.argocd.namespace }}
spec:
  destinations:
  - name: {{ .Values.application.destination.name }}
    namespace: {{ .Values.application.destination.namespace }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - description: read-only group
    groups:
    - {{ .Values.environment.roGroup }}
    name: ro-group
    policies:
    - p, proj:{{ .Values.argocd.project }}-env:ro-group, applications, get, {{ .Values.argocd.project }}-env/*,
      allow
  - description: read-write group
    groups:
    - {{ .Values.environment.rwGroup }}
    name: rw-group
    policies:
    - p, proj:{{ .Values.argocd.project }}-env:rw-group, applications, *, {{ .Values.argocd.project }}-env/*,
      allow
    - p, proj:{{ .Values.argocd.project }}-env:rw-group, applications, delete, {{ .Values.argocd.project }}-env/*,
      allow
    - p, proj:{{ .Values.argocd.project }}-env:rw-group, applications, create, {{ .Values.argocd.project }}-env/*,
      deny
  sourceRepos:
    - https://github.com/cloud-pi-native/console.git
    - {{ .Values.environment.valueFileRepository }}
    - {{ .Values.application.gitlabGroup }}/*

