import { getProjectbyId } from '../support/func.js'

const project = getProjectbyId('011e7860-04d7-461f-912d-334c622d38b3')

describe('Sidebar', () => {
  it('Should display Sidebar, not loggedIn', () => {
    cy.visit('/')
      .getByDataTestid('mainMenu').should('be.visible')
      .getByDataTestid('menuProjectsList').should('not.exist')
      .getByDataTestid('menuProjectsBtn').should('not.exist')
      .getByDataTestid('menuDoc').click()
      .getByDataTestid('menuProjectsBtn').should('not.exist')
      .url().should('contain', '/doc')
      .getByDataTestid('menuDoc').should('have.class', 'router-link-active')
  })
  it('Should display Sidebar, loggedIn', () => {
    cy.kcLogin('test')

    cy.visit('/')
      .getByDataTestid('mainMenu').should('be.visible')
      .getByDataTestid('menuProjectsList').should('not.be.visible')
      .getByDataTestid('menuProjectsBtn').click()
      .getByDataTestid('menuProjectsList').should('be.visible')
      .getByDataTestid('menuMyProjects').click()
      .url().should('contain', '/projects')
      .getByDataTestid(`projectTile-${project.name}`).click()
      .getByDataTestid('menuProjectsList').should('be.visible')
      .url().should('contain', `/projects/${project.id}/services`)
      .getByDataTestid('menuDashboard').click()
      .getByDataTestid('menuProjectsList').should('be.visible')
      .url().should('contain', `/projects/${project.id}/dashboard`)
      .getByDataTestid('menuTeam').click()
      .getByDataTestid('menuProjectsList').should('be.visible')
      .url().should('contain', `/projects/${project.id}/team`)
      .getByDataTestid('menuRepos').click()
      .getByDataTestid('menuProjectsList').should('be.visible')
      .url().should('contain', `/projects/${project.id}/repositories`)
      // TODO : deskip lorsque les playbooks seront intégrés
      // .getByDataTestid('menuEnvironments').click()
      // .getByDataTestid('menuProjectsList').should('be.visible')
      // .url().should('contain', `/projects/${project.id}/environments`)
      .getByDataTestid('menuDoc').click()
      .getByDataTestid('menuProjectsList').should('not.be.visible')
      .url().should('contain', '/doc')
      .getByDataTestid('menuDoc').should('have.class', 'router-link-active')
  })
})
