shellEmulator: true
trustPolicy: no-downgrade

# Check these after each update. This list should be empty !
trustPolicyExclude:
  - rollup@2.80.0
  - semver@6.3.1
  - chokidar@4.0.3

autoInstallPeers: true
injectWorkspacePackages: true
packages:
  - "packages/**"
  - "plugins/**"
  - "apps/**"
  - "!apps/server/src/plugins/external/**"
  - "playwright/**"
patchedDependencies:
  "@gouvminint/vue-dsfr": patches/@gouvminint__vue-dsfr.patch
  fastify-keycloak-adapter@2.3.2: patches/fastify-keycloak-adapter@2.3.2.patch
allowUnusedPatches: true
