export {
  RiCloseLine,
  RiFlagLine,
  RiHome2Line,
  RiHome4Line,
  RiRefreshLine,
  RiUploadCloudLine,
  RiSendPlaneLine,
  RiDeleteBin7Line,
  RiAddLine,
  RiUserAddLine,
  RiFileSettingsLine,
  RiFileCopy2Line,
  RiRefreshFill,
  RiSunLine,
  RiMoonClearLine,
  RiPencilFill,
  RiExchangeLine,
  RiCheckFill,
  RiUserStarFill,
  RiUserFill,
} from 'oh-vue-icons/icons/ri/index.js'
