export const INFRA_GROUP_NAME = 'Infra'
export const INFRA_GROUP_PATH = 'infra'
export const INFRA_APPS_REPO_NAME = 'infra-apps'
export const MIRROR_REPO_NAME = 'mirror'
export const TOPIC_PLUGIN_MANAGED = 'plugin-managed'
export const TOKEN_DESCRIPTION = 'mirroring-from-external-repo'

export const DEFAULT_ADMIN_GROUP_PATH = '/console/admin'
export const DEFAULT_AUDITOR_GROUP_PATH = '/console/readonly'
export const DEFAULT_PROJECT_MAINTAINER_GROUP_PATH_SUFFIX = '/console/admin'
export const DEFAULT_PROJECT_DEVELOPER_GROUP_PATH_SUFFIX = '/console/developer,/console/devops'
export const DEFAULT_PROJECT_REPORTER_GROUP_PATH_SUFFIX = '/console/readonly'
