---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
      {{- if .Values.db.expose }}
      - containerPort: 30432
        hostPort: {{ .Values.db.hostPort }}
        protocol: TCP
      {{- end }}
    extraMounts:
      - hostPath: ./
        containerPath: /app
      {{- if .Values.plugins.mount }}
      - hostPath: {{ .Values.plugins.localDir }}
        containerPath: /plugins
      {{- end }}
