---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Release.Name }}-console-clusterrole
rules:
- apiGroups:
  - ""
  - user.openshift.io
  - rbac.authorization.k8s.io
  - argoproj.io
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Release.Name }}-console-clusterole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Release.Name }}-console-clusterrole
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}-console-sa
  namespace: {{ $.Release.Namespace }}
