kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-ansible-cm
data:
  {{- include "globalEnv" $.Values | indent 2 }}
  {{- with .Values.containers.ansible.container }}
  HOME: /home/node/
  PLAYBOOK_DIR: {{ .playbooks.repoDir}}
  ANSIBLE_PORT: {{ .port | quote }}
  NODE_ENV: {{ .node_env }}
  INVENTORY_NAMESPACE: {{ .playbooks.inventory.namespace }}
  INVENTORY_NAME: {{ .playbooks.inventory.name }}
  INVENTORY_KEY: {{ .playbooks.inventory.key }}
  {{- end }}
  {{- with .Values.keycloak }}
  SESSION_SECRET: {{ .session_secret }}
  KEYCLOAK_DOMAIN: {{ .domain }}
  KEYCLOAK_REALM: {{ .realm }}
  KEYCLOAK_PROTOCOL: https
  KEYCLOAK_CLIENT_ID: {{ .client_id_backend }}
  KEYCLOAK_CLIENT_SECRET: {{ .client_secret_backend }}
  KEYCLOAK_REDIRECT_URI: {{ .redirect_uri }}
  {{- end }}
