kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-client-cm
data: 
  {{- include "globalEnv" $.Values | indent 2 }}
  {{- include "containerEnv" .Values.client.container | indent 2 }}
  {{- with .Values.server.service }}
  SERVER_HOST: {{ $.Release.Name }}-{{ .hostname }}-service
  SERVER_PORT: {{ .port | quote }}
  {{- end }}
