---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-client-cm
data:
  NODE_ENV: {{ .Values.env }}
  {{- with .Values.keycloak }}
  KEYCLOAK_PROTOCOL: {{ .protocol }}
  KEYCLOAK_DOMAIN: {{ .domain }}
  KEYCLOAK_REALM: {{ .realm }}
  KEYCLOAK_CLIENT_ID: {{ .clientIdFrontend }}
  KEYCLOAK_REDIRECT_URI: {{ .redirectUri }}
  {{- end }}
  {{- with .Values.server.service }}
  SERVER_HOST: {{ $.Release.Name }}-{{ .hostname }}-service
  SERVER_PORT: {{ .port | quote }}
  {{- end }}
  {{- include "globalEnv" .Values | indent 2 }}
  {{- include "containerEnv" .Values.client.container | indent 2 }}
