---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-postgres-cm
data:
  {{- with .Values.postgres }}
  POSTGRES_DB: {{ .container.db }}
  POSTGRES_USER: {{ .container.user }}
  POSTGRES_PASSWORD: {{ .container.pass }}
  PGDATA: /var/lib/postgresql/data/pgdata
  {{- end }}
  {{- include "globalEnv" $.Values | indent 2 }}
  {{- include "containerEnv" .Values.postgres.container | indent 2 }}
