kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-server-cm
data:
  {{- include "globalEnv" .Values | indent 2 }}
  {{- include "containerEnv" .Values.containers.server.container | indent 2 }}
  SERVER_PORT: {{ .Values.containers.server.container.port | quote }}
  {{- with .Values.containers.postgres }}
  DB_HOST: {{ $.Release.Name }}-{{ .service.hostname }}-service
  DB_PORT: {{ .service.port | quote }}
  DB_USER: {{ .container.user }}
  DB_PASS: {{ .container.pass }}
  DB_NAME: {{ .container.db }}
  {{- end }}
  {{- with .Values.keycloak }}
  SESSION_SECRET: {{ .session_secret }}
  KEYCLOAK_DOMAIN: {{ .domain }}
  KEYCLOAK_REALM: {{ .realm }}
  KEYCLOAK_PROTOCOL: https
  KEYCLOAK_CLIENT_ID: {{ .client_id_backend }}
  KEYCLOAK_CLIENT_SECRET: {{ .client_secret_backend }}
  KEYCLOAK_REDIRECT_URI: {{ .redirect_uri }}
  {{- end }}
  {{- with .Values.containers.ansible.service }}
  ANSIBLE_HOST: {{ $.Release.Name }}-{{ .hostname }}-service
  ANSIBLE_PORT: {{ .port | quote }}
  {{- end }}
  NODE_ENV: production
  HOME: /home/node