{{- if  .Values.server.plugins }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-fetch-script
data:
  fetch: |
    #!/bin/bash
    cd /tmp
{{- range $i, $val := .Values.server.plugins }}
    wget {{ $val }} -O {{ $i }}.zip;
    mkdir -p /plugins/{{ $i }}
    unzip {{ $i }}.zip -d /plugins/{{ $i }};
{{- end }}
{{- end }}