---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-server-cm
data:
  NODE_ENV: {{ .Values.env }}
  HOME: /home/node
  {{- with .Values.keycloak }}
  SESSION_SECRET: {{ .sessionSecret }}
  KEYCLOAK_DOMAIN: {{ .domain }}
  KEYCLOAK_REALM: {{ .realm }}
  KEYCLOAK_PROTOCOL: {{ .protocol }}
  KEYCLOAK_CLIENT_ID: {{ .clientIdBackend }}
  KEYCLOAK_CLIENT_SECRET: {{ .clientSecretBackend }}
  KEYCLOAK_REDIRECT_URI: {{ .redirectUri }}
  {{- end }}
  SERVER_PORT: {{ .Values.server.container.port | quote }}
  {{- with .Values.postgres }}
  DB_HOST: {{ $.Release.Name }}-{{ .service.hostname }}-service
  DB_URL: postgresql://{{ .container.user }}:{{ .container.pass }}@{{ $.Release.Name }}-{{ .service.hostname }}-service:{{ .service.port }}/{{ .container.db }}?schema=public 
  {{- end }}
  {{- if .Values.server.extraCa.name }}
  NODE_EXTRA_CA_CERTS: /config/ca_certs
  {{- end }}
  {{- include "containerEnv" .Values.server.container | indent 2 }}
