{{- if  .Values.server.plugins }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-fetch-script
data:
  fetch: |
    #!/bin/bash
    cd /tmp
{{- range $i, $val := .Values.server.plugins }}
    wget {{ $val }} -O {{ $i }}.zip;
    unzip {{ $i }}.zip -d /plugins;
{{- end -}}
{{- end -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-server
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Release.Name }}-pullsecret
{{- with .Values.server }}
{{- if  .plugins }}
      initContainers:
      - image: busybox
        command:
        - sh
        - /script/fetch
        volumesMounts:
          - name: fetch-script
            mountDir: /script
          - name: plugins
            mountDir: /plugins
{{- end }}
      containers:
      - image: {{ .container.image }}
        imagePullPolicy: Always
        name: {{ $.Release.Name }}-server
        ports:
        - containerPort: {{ .container.port }}
        envFrom:
        - configMapRef:
            name: {{ $.Release.Name }}-server-cm
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .container.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /healthz
            port: {{ .container.port }}
          failureThreshold: 10
          periodSeconds: 4
        volumeMounts:
{{- if .container.data_configmap }}
          - name: imports
            mountPath: /app/src/init/db/imports
{{- end }}
{{- if and .plugins (len .plugins) }}
          - name: plugins
            mountPath: /app/src/plugins/external
{{- end }}
      volumes:
{{- if .container.data_configmap }}
        - name: imports
          configMap: 
            name: {{ .container.data_configmap }}
{{- end }}
{{- if and .plugins (len .plugins) }}
        - name: plugins
          emptyDir: {}
        - name: fetch-script
          configMap:
            name: {{ $.Release.Name }}-fetch-script
{{- end }}
{{- end -}}