apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-client
  name: {{ .Release.Name }}-client
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      imagePullSecrets:
      - name: {{ .Release.Name }}-pullsecret
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-client-cm
        name: {{ .Release.Name }}-client
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.client.container.image }}
        ports:
        - containerPort: {{ .Values.client.container.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: env
            mountPath: /env/
      volumes:
        - name: env
          configMap:
            name: {{ $.Release.Name }}-client-app-cm

