apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dso-db-storage # TODO
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi