{{ $containers := list "server" "client" "postgres" }}
{{- range $container := $containers -}}
{{- with index $.Values $container }}
  
{{- if .route -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Release.Name }}-{{ $container }}-route
spec:
  host: {{ .route.host }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ $.Release.Name }}-{{ $container }}-service
  wildcardPolicy: None
{{- end -}}
{{- end -}}
{{- end -}}