{{ $containers := list "server" "client" "postgres" }}
{{- range $container := $containers -}}
{{- with index $.Values $container }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $container }}-service
spec:
  type: {{ .service.type}}
  selector:
    app: {{ $.Release.Name }}-{{ $container }}
  ports:
  - port: {{ .service.port }}
    targetPort: {{ .container.port }}
    nodePort: {{ .service.nodePort }}
{{- end }}
{{- end }}
