name: Vulnerability scan

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: false
        type: string
      PNPM_VERSION:
        required: false
        type: string

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.build-matrix.outputs.BUILD_MATRIX }}
      scan-matrix: ${{ steps.scan-matrix.outputs.SCAN_MATRIX }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Generate matrix
        id: build-matrix
        run: |
          echo 'BUILD_MATRIX<<EOF' >> $GITHUB_OUTPUT
          ./ci/scripts/build-matrix.sh -f ./docker/docker-compose.prod.yml -c | jq '[.[] | select(.build != false)]' >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Generate matrix
        id: scan-matrix
        run: |
          echo 'SCAN_MATRIX<<EOF' >> $GITHUB_OUTPUT
          ./ci/scripts/build-matrix.sh -f ./docker/docker-compose.prod.yml -c >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

  build:
    name: Build application
    runs-on: ubuntu-latest
    needs:
      - matrix
    strategy:
      matrix:
        images: ${{ fromJSON(needs.matrix.outputs.build-matrix) }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for multi platform build)
        uses: docker/setup-qemu-action@v3

      - name: Create image directory
        run: mkdir ./artifacts

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.images.build.context }}
          file: ${{ matrix.images.build.dockerfile }}
          tags: ${{ matrix.images.image }}
          target: ${{ matrix.images.build.target }}
          platforms: ${{ matrix.images.build.platforms }}
          outputs: type=docker,dest=./artifacts/${{ matrix.images.name }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.images.name }}
          path: ./artifacts/${{ matrix.images.name }}.tar
          retention-days: 1

  images-scan:
    name: Scan images vulnerabilities
    runs-on: ubuntu-latest
    needs:
      - matrix
      - build
    strategy:
      matrix:
        images: ${{ fromJSON(needs.matrix.outputs.scan-matrix) }}
    steps:
      - name: Set up Docker buildx
        if: ${{ matrix.images.build != false }}
        uses: docker/setup-buildx-action@v3

      - name: Download artifact
        if: ${{ matrix.images.build != false }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.images.name }}
          path: ./artifacts

      - name: Load Docker image
        if: ${{ matrix.images.build != false }}
        run: docker load --input ./artifacts/${{ matrix.images.name }}.tar

      - name: Create security artifacts directory
        run: mkdir -p ./artifacts/vulnerability-report/images/

      - name: Run Trivy vulnerability scanner on images
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ matrix.images.image }}"
          format: "json"
          exit-code: "1"
          vuln-type: "os,library"
          ignore-unfixed: true
          output: "./artifacts/vulnerability-report/images/${{ matrix.images.name }}.json"
        continue-on-error: true

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: ./artifacts/vulnerability-report/
          retention-days: 14

  config-scan:
    name: Scan config files vulnerabilities
    runs-on: ubuntu-latest
    needs:
      - matrix
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Create security artifacts directory
        run: mkdir -p ./artifacts/vulnerability-report/configs/

      - name: Run Trivy vulnerability scanner on config files
        uses: aquasecurity/trivy-action@master
        with:
          scan-ref: "."
          scan-type: "config"
          format: "json"
          exit-code: "1"
          ignore-unfixed: true
          output: "./artifacts/vulnerability-report/configs/config.json"
        continue-on-error: true

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: ./artifacts/vulnerability-report/
          retention-days: 14

  vulnerability-report:
    name: Build vulnerability report
    runs-on: ubuntu-latest
    needs:
      - matrix
      - images-scan
      - config-scan
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vulnerability-report
          path: ./artifacts/vulnerability-report

      - name: Build vulnerability report
        run: |
          ./ci/scripts/vuln-report.sh \
            -i "./artifacts/vulnerability-report" \
            -o "./artifacts/vulnerability-issue.md" \
            -p "${{ github.repository }}" \
            -r "${{ github.run_id }}"
          echo 'REPORT_BODY<<EOF' >> $GITHUB_ENV
          cat ./artifacts/vulnerability-issue.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create security report issue
        uses: imjohnbo/issue-bot@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: "security"
          title: "Vulnerability scan report"
          pinned: false
          close-previous: true
          body: ${{ env.REPORT_BODY }}
