name: Tests - e2e

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      PNPM_VERSION:
        required: true
        type: string
    secrets:
      SONAR_HOST_URL:
        required: false
      SONAR_TOKEN:
        required: false
      SONAR_PROJECT_KEY:
        required: false

jobs:
  e2e-tests:
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: "${{ inputs.PNPM_VERSION }}"
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.NODE_VERSION }}"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run e2e tests
        run: |
          ./ci/scripts/init-env.sh
          ./ci/scripts/run-tests.sh -e

      - name: Give permissions to upload logs
        if: ${{ failure() }}
        run: |
          mkdir ./logs
          sudo find /var/lib/docker/containers/ -name "*.log" -exec cp "{}" ./logs  \;
          sudo chmod 777 -R ./logs

      - name: Upload cypress artifacts and logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: |
            ./apps/client/cypress/e2e/screenshots/
            ./logs/
          retention-days: 14
