name: Test application

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - "**"

env:
  NODE_VERSION: "lts/*"

jobs:
  unit-tests:
    name: Run unit test suite
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE_VERSION }}"
          check-latest: true
      - name: Install dependencies
        run: ./ci/scripts/init-project.sh -c -e ./cypress -e .
      - name: Run unit tests
        run: ./ci/scripts/run-tests.sh -u ./client

  code-scan:
    name: Run code quality analysis
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scan code
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN }} \
            -v $PWD/:/usr/src/app \
            sonarsource/sonar-scanner-cli sonar-scanner \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.branch.name=${{ github.event.pull_request.head.ref }} \
              -Dsonar.qualitygate.wait=true \
              -Dsonar.projectBaseDir=/usr/src/app \
              -Dsonar.sources=client \
              -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info \
              -Dsonar.coverage.exclusions=**/*.spec.js,**/*.vue,client/src/router/**,client/src/stores/**,client/src/components/**,client/src/views/**,client/src/assets/**,client/src/main.js,client/src/icons.js

  e2e-tests:
    name: Run e2e test suite
    runs-on: ubuntu-latest
    needs:
      - code-scan
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Run e2e tests
        run: ./ci/scripts/run-tests.sh -e
        continue-on-error: true
      - name: Upload cypress artifacts
        uses: actions/upload-artifact@v3
        with:
          name: e2e-report
          path: ./cypress/e2e/screenshots/
