name: Tests - unit

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      PNPM_VERSION:
        required: true
        type: string
    secrets:
      SONAR_HOST_URL:
        required: false
      SONAR_TOKEN:
        required: false
      SONAR_PROJECT_KEY:
        required: false

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: "${{ inputs.PNPM_VERSION }}"
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ inputs.NODE_VERSION }}"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: |
          ./ci/scripts/init-env.sh
          ./ci/scripts/run-tests.sh -u

      - name: Upload vitest coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-coverage
          path: |
            ./apps/**/coverage
            ./packages/**/coverage
          retention-days: 1

  check-secrets:
    name: Check if Sonar secrets are set
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    outputs:
      run-scan: ${{ steps.check-secrets.outputs.run-scan }}
    steps:
      - name: Check secrets presence
        id: check-secrets
        run: |
          if [ "${{ secrets.SONAR_HOST_URL }}" != "" ] && [ "${{ secrets.SONAR_TOKEN }}" != "" ] && [ "${{ secrets.SONAR_PROJECT_KEY }}" != "" ]; then
            echo "run-scan=true" >> $GITHUB_OUTPUT
          else
            echo "run-scan=false" >> $GITHUB_OUTPUT
          fi

  code-scan:
    name: Run code quality analysis
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - check-secrets
    if: ${{ needs.check-secrets.outputs.run-scan == 'true' }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: unit-tests-coverage
          path: ./coverage

      - name: Scan code
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN }} \
            -v $PWD/:/usr/src \
            sonarsource/sonar-scanner-cli sonar-scanner \
              -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
              -Dsonar.branch.name=${{ github.event.pull_request.head.ref }} \
              -Dsonar.qualitygate.wait=true \
              -Dsonar.projectBaseDir=/usr/src \
              -Dsonar.sources=./apps,./packages \
              -Dsonar.javascript.lcov.reportPaths=coverage/**/coverage/lcov.info \
              -Dsonar.coverage.exclusions=**/*.spec.js,**/*.spec.ts,**/*.vue,**/assets/**,**/cypress/**
        continue-on-error: true
