-- AlterTable
ALTER TABLE "Project"
ADD COLUMN     "limitless" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hprodCpu" REAL NOT NULL DEFAULT 0,
ADD COLUMN     "hprodGpu" REAL NOT NULL DEFAULT 0,
ADD COLUMN     "hprodMemory" REAL NOT NULL DEFAULT 0,
ADD COLUMN     "prodCpu" REAL NOT NULL DEFAULT 0,
ADD COLUMN     "prodGpu" REAL NOT NULL DEFAULT 0,
ADD COLUMN     "prodMemory" REAL NOT NULL DEFAULT 0;
