server:
  container:
    env:
      KUBECONFIG_CTX:
      KUBECONFIG_PATH: /home/node/.kube/config
      CI: "false"
      INTEGRATION: "true"
      KEYCLOAK_REDIRECT_URI: http://console.dso.local
      KEYCLOAK_PROTOCOL: https
      KEYCLOAK_CLIENT_ID:
      KEYCLOAK_CLIENT_SECRET:
      KEYCLOAK_DOMAIN:
      KEYCLOAK_REALM:
      ARGO_NAMESPACE:
      ARGOCD_URL:
      DSO_ENV_CHART_VERSION:
      DSO_NS_CHART_VERSION:
      GITLAB_TOKEN:
      GITLAB_URL:
      HARBOR_ADMIN:
      HARBOR_ADMIN_PASSWORD:
      HARBOR_URL:
      KEYCLOAK_ADMIN:
      KEYCLOAK_ADMIN_PASSWORD:
      KEYCLOAK_URL:
      NEXUS_ADMIN:
      NEXUS_ADMIN_PASSWORD:
      NEXUS_URL:
      PROJECTS_ROOT_DIR:
      SONAR_API_TOKEN:
      SONARQUBE_URL:
      VAULT_TOKEN:
      VAULT_URL:
    extraVolumes:
      - name: dev-workspace
        path: /app/apps/server/src
        type: hostPath
      - name: kubeconfig-integ-cm
        type: configMap
    extraVolumeMounts:
      - name: dev-workspace
        mountPath: /app/apps/server/src
      - name: kubeconfig-integ-cm
        mountPath: /home/node/.kube/

client:
  container:
    env:
      INTEGRATION: "true"
      KEYCLOAK_REDIRECT_URI: http://console.dso.local
      KEYCLOAK_PROTOCOL: https
      KEYCLOAK_CLIENT_ID:
      KEYCLOAK_REALM:
      KEYCLOAK_DOMAIN:
    extraVolumes:
      - name: dev-workspace
        path: /app/apps/client/src
        type: hostPath
    extraVolumeMounts:
      - name: dev-workspace
        mountPath: /app/apps/client/src

keycloak:
  enabled: false
