export * from '@/resources/admin-role/queries.js'
export * from '@/resources/cluster/queries.js'
export * from '@/resources/environment/queries.js'
export * from '@/resources/log/queries.js'
export * from '@/resources/organization/queries.js'
// export * from '@/resources/permission/queries.js'
export * from '@/resources/project/queries.js'
export * from '@/resources/project-member/queries.js'
export * from '@/resources/project-role/queries.js'
export * from '@/resources/project-service/queries.js'
export * from '@/resources/quota/queries.js'
export * from '@/resources/repository/queries.js'
export * from '@/resources/stage/queries.js'
export * from '@/resources/system/settings/queries.js'
export * from '@/resources/user/queries.js'
export * from '@/resources/zone/queries.js'
