version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:14.5
    container_name: dso-console_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-dso-console-db}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    # ports:
    #   - 5432:5432
    volumes: 
      - ../db/data:/var/lib/postgresql/data
    networks:
      - dso-network
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: dso-console_keycloak
    ports:
      - 8090:8080
    volumes:
      - ../keycloak/realms:/opt/keycloak/data/import
      # - ../keycloak/data:/opt/keycloak/data/h2
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    command: start-dev --import-realm
    networks:
      - dso-network
  
  pgadmin:
    restart: always
    image: dpage/pgadmin4:latest
    container_name: dso-console_pgadmin
    depends_on:
      - postgres
    volumes:
        - ../db/pgadmin/data:/var/lib/pgadmin
    ports: 
      - 8081:80
    environment:
      # PGADMIN_SERVER_JSON_FILE
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@dso.fr}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    # command: sh -c chown 5050:5050 /var/lib/pgadmin
    networks:
      - dso-network
  server:
    restart: always
    build:
      context: server
      dockerfile: Dockerfile
      target: dev
    image: dso-console/server:dev
    container_name: dso-console_server
    depends_on:
      - keycloak
      - postgres
    ports:
      - 4000:4000
    volumes:
      - ../server:/app/
      - /app/node_modules/
    environment:
      SERVER_PORT: ${SERVER_PORT:-4000}
      NODE_ENV: development
    networks:
      - dso-network

  client:
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
      target: dev
    image: dso-console/client:dev
    container_name: dso-console_client
    depends_on:
      - server
    ports:
      - 8080:8080
    volumes:
      - ../client:/app/
      - /app/node_modules/
    environment:
      KEYCLOAK_HOST: ${KEYCLOAK_HOST:-localhost}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT:-8090}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-TEST}
      KEYCLOAK_CLIENTID: ${KEYCLOAK_CLIENTID:-TEST}
    networks:
      - dso-network

networks:
  dso-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
