version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
      target: dev
    image: dso-console/client
    container_name: dso-console_client
    ports:
      - 8080:8080
    volumes:
      - ../client:/app/
      - /app/node_modules/
    command: npm run dev
    networks:
      - dso-network

networks:
  dso-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
