version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    # container_name: ${APP}_keycloak
    volumes:
      - ../sso/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev --import-realm
    # command: start
    ports:
      - 8090:8080
    networks:
      - dso-network

  client:
    build:
      context: client
      dockerfile: Dockerfile
      target: dev
    image: dso-console/client
    container_name: dso-console_client
    ports:
      - 8080:8080
    volumes:
      - ../client:/app/
      - /app/node_modules/
    command: npm run dev
    networks:
      - dso-network
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8090
      - KEYCLOAK_REALM=TEST
      - KEYCLOAK_CLIENTID=TEST

networks:
  dso-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
