version: '3.9'

services:
  postgres:
    restart: always
    image: docker.io/postgres:15.3
    container_name: dso-console_postgres
    environment:
      POSTGRES_DB: dso-console-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - dso-network

  server:
    restart: always
    build:
      context: ..
      dockerfile: apps/server/Dockerfile
      target: prod
    image: dso-console/server:prod
    container_name: dso-console_server
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 4000:4000
    # volumes:
    #   - ../apps/server/env/.env:/env/.env
    networks:
      - dso-network

  client:
    build:
      context: ..
      dockerfile: apps/client/Dockerfile
      target: prod
    image: dso-console/client:prod
    container_name: dso-console_client
    depends_on:
      server:
        condition: service_started
    ports:
      - 8080:8080
    # volumes:
    #   - ../apps/client/env/.env:/env/.env
    networks:
      - dso-network

networks:
  dso-network:
    name: dso-network
