version: '3.9'

services:
  cypress:
    image: cypress/included:10.8.0
    container_name: dso-console_cypress
    depends_on:
      - client
    working_dir: /app
    volumes:
      - ../packages/cypress:/app
    environment:
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PORT: ${CLIENT_PORT}
      NODE_ENV: test
    networks:
      - dso-network

networks:
  dso-network:
    name: dso-network
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
