version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:14.5
    container_name: dso-console_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - dso-network

  server:
    restart: always
    build:
      context: ..
      dockerfile: apps/server/Dockerfile
      target: prod
    image: dso/console/server
    container_name: dso-console_server
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 4000:80
    environment:
      SERVER_PORT: 80
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
      SESSION_SECRET: ${SESSION_SECRET}
      KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_BACKEND}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET_BACKEND}
      KEYCLOAK_REDIRECT_URI: ${KEYCLOAK_REDIRECT_URI}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER:-admin}
      ANSIBLE_HOST: ansible-api
      ANSIBLE_PORT: ${ANSIBLE_PORT}
      NODE_ENV: production
      INVENTORY: dev
    networks:
      - dso-network

  ansible-api:
    restart: always
    build:
      context: ..
      dockerfile: apps/ansible-api/Dockerfile
      target: prod
    image: dso/console/ansible
    container_name: dso-console_ansible-api
    ports:
      - 8100:8100
    volumes:
      - ../ansible/playbooks:${PLAYBOOK_DIR:-/dso}
    environment:
      PLAYBOOK_DIR: ${PLAYBOOK_DIR:-/dso}
      CONFIG_DIR: ${CONFIG_DIR:-/config}
      CLONE_DIR: ${CLONE_DIR:-/dso}
      ANSIBLE_PORT: ${ANSIBLE_PORT}
      SESSION_SECRET: ${SESSION_SECRET:-a-very-strong-secret-with-more-than-32-char}
      KEYCLOAK_PROTOCOL: ${KEYCLOAK_PROTOCOL:-http}
      KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-cloud-pi-native}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_ANSIBLE:-dso-console-ansible-api}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET_ANSIBLE:-client-secret-ansible-api}
      NODE_ENV: production
    networks:
      - dso-network

  client:
    build:
      context: ..
      dockerfile: apps/client/Dockerfile
      target: prod
    image: dso/console/client
    container_name: dso-console_client
    depends_on:
      server:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_PROTOCOL: ${KEYCLOAK_PROTOCOL}
      KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_FRONTEND}
      KEYCLOAK_REDIRECT_URI: ${KEYCLOAK_REDIRECT_URI}
      SERVER_HOST: server
      SERVER_PORT: 80
      ARGOCD_URL: ${ARGOCD_URL:-https://argo-cd.readthedocs.io}
      GITLAB_URL: ${GITLAB_URL:-https://gitlab.com}
      NEXUS_URL: ${NEXUS_URL:-https://sonatype.com/products/nexus-repository}
      QUAY_URL: ${QUAY_URL:-https://quay.io}
      SONARQUBE_URL: ${SONARQUBE_URL:-https://www.sonarqube.org}
      VAULT_URL: ${VAULT_URL:-https://www.vaultproject.io}
    networks:
      - dso-network

networks:
  dso-network:
    name: dso-network
