# Ajouter server, db et keycloak

version: '3.8'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
      target: prod
    image: dso-console/client
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENTID: ${KEYCLOAK_CLIENTID}
    networks:
      - dso-network

networks:
  dso-network:
    name: dso-network
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
