version: '3.9'

services:
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: dso-console_keycloak
    ports:
      - 8090:8080
    volumes:
      - ../keycloak/realms:/opt/keycloak/data/import
      - ../keycloak/data:/opt/keycloak/data/h2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - dso-network

  postgres:
    restart: always
    image: docker.io/postgres:15.3
    container_name: dso-console_postgres
    environment:
      POSTGRES_DB: dso-console-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - dso-postgres-data:/var/lib/postgresql/data
    networks:
      - dso-network

  pgadmin:
    restart: always
    image: docker.io/dpage/pgadmin4:7.4
    container_name: dso-console_pgadmin
    depends_on:
      - postgres
    volumes:
      - dso-pgadmin-data:/var/lib/pgadmin
      - ../db/pgadmin/config/servers.json:/pgadmin4/servers.json
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dso.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - dso-network

  server:
    restart: always
    build:
      context: ..
      dockerfile: apps/server/Dockerfile
      target: dev
    image: dso-console/server:dev
    container_name: dso-console_server
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - /app/node_modules/
      - ../apps/server:/app/apps/server
      - /app/apps/server/node_modules/
    environment:
      NODE_ENV: development
    networks:
      - dso-network

  client:
    restart: always
    build:
      context: ..
      dockerfile: apps/client/Dockerfile
      target: dev
    image: dso-console/client:dev
    container_name: dso-console_client
    depends_on:
      - server
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules/
      - ../apps/client:/app/apps/client
      - /app/apps/client/node_modules/
    environment:
      NODE_ENV: development
    networks:
      - dso-network

networks:
  dso-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450

volumes:
  dso-keycloak-data:
  dso-pgadmin-data:
  dso-postgres-data:
