# TODO : Ajouter server, db et keycloak

version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:14.5
    container_name: dso-console_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../db/postgres/scripts:/docker-entrypoint-initdb.d
    networks:
      - dso-network

  server:
    restart: always
    build:
      # context: apps/server
      # dockerfile: Dockerfile
      context: ..
      dockerfile: apps/server/Dockerfile
      target: prod
    image: dso-console/server
    container_name: dso-console_server
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - 4000:4000
    environment:
      SERVER_PORT: ${SERVER_PORT}
      NODE_ENV: production
    networks:
      - dso-network

  client:
    build:
      # context: apps/client
      # dockerfile: Dockerfile
      context: ..
      dockerfile: apps/client/Dockerfile
      target: prod
    image: dso-console/client
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENTID: ${KEYCLOAK_CLIENTID}
    networks:
      - dso-network

networks:
  dso-network:
    name: dso-network
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
