version: '3.9'

services:
  postgres:
    restart: always
    image: docker.io/postgres:14.5
    container_name: dso-console_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - dso-network

  server:
    restart: always
    build:
      context: ..
      dockerfile: apps/server/Dockerfile
      target: prod
    image: dso/console/server
    container_name: dso-console_server
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_started
    ports:
      - 4000:4000
    env_file:
      - ../env/.env
      - ../apps/server/env/.env
    # volumes:
    #   - ../apps/server/env/.env:/app/.env
    environment:
      NODE_ENV: production
    networks:
      - dso-network

  client:
    build:
      context: ..
      dockerfile: apps/client/Dockerfile
      target: prod
    image: dso/console/client
    container_name: dso-console_client
    depends_on:
      server:
        condition: service_started
    ports:
      - 8080:8080
    # volumes:
    #   - ../apps/client/env/.env:/env
    env_file:
      - ../env/.env
      - ../apps/client/env/.env
    environment:
      NODE_ENV: production
    networks:
      - dso-network

networks:
  dso-network:
    name: dso-network
