version: '3.9'

services:
  cypress:
    build:
      context: ..
      dockerfile: apps/client/cypress/Dockerfile
      target: build
    image: dso-console/cypress:ci
    container_name: dso-console_cypress
    volumes:
      - /app/node_modules/
      - ../apps/client:/app/apps/client
      - /app/apps/client/node_modules/
      - ../packages/shared:/app/packages/shared
      - /app/packages/shared/node_modules/
    environment:
      NODE_ENV: test
      CT: 'true'
    command: cypress:run-ct --browser chrome
    networks:
      - dso-network

networks:
  dso-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450
