# Variables nécessaires :
# - PROJECT_NAME
# - ORGANIZATION_NAME
# - EMAIL
- name: Create project
  hosts: localhost
  vars:
    validation:
      required: ["PROJECT_NAME", "ORGANIZATION_NAME","EMAIL"]
      type: object
      properties:
        PROJECT_NAME:
          type: string
        ORGANIZATION_NAME:
          type: string
        EMAIL:
          type: string
        ENV_LIST:
          type: array
          items:
            type: string
  tasks:
    - name: Create a project
      ansible.builtin.debug:
        msg:
        - "Create a project"