# Variables nécessaires :
# - PROJECT_NAME
# - ORGANIZATION_NAME
# - EMAIL
# - ENV_LIST (optionnel)
# 
# Point de vigilence :
# - S'assurer qu'on ne tente pas de supprimer le owner.

- name: Remove a user from a project
  hosts: localhost
  vars:
    validation:
      required: ["PROJECT_NAME", "ORGANIZATION_NAME", "EMAIL", "ENV_LIST"]
      type: object
      properties:
        PROJECT_NAME:
          type: string
        ORGANIZATION_NAME:
          type: string
        EMAIL:
          type: string
        ENV_LIST:
          type: array
          items:
            type: string

  tasks:
    - name: Remove a user from a project
      ansible.builtin.debug:
        msg:
        - "Remove a user from a project"