version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    # container_name: ${APP}_keycloak
    volumes:
       - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KEYCLOAK_IMPORT=/tmp/keycloak/import-realm.json
      # - PROXY_ADDRESS_FORWARDING=true
    command: start-dev --import-realm
    # command: start
    ports:
      - 8090:8080
    networks:
      - dso-network
      
networks:
  dso-network:
    driver: bridge
    # driver_opts:
    # com.docker.network.driver.mtu: 1450