describe('Sidebar', () => {
  it('Should display Sidebar', () => {
    cy.visit('/')
      .getByDataTestid('menuPrincipal')
      .should('be.visible')
      .getByDataTestid('menuMesProjetsList')
      .should('not.be.visible')
      .getByDataTestid('menuMesProjetsBtn').click()
      .getByDataTestid('menuMesProjetsList')
      .should('be.visible')
      .getByDataTestid('menuDashboard').click()
      .url().should('contain', '/tableau-de-bord')
      .getByDataTestid('menuMesProjetsList')
      .should('not.be.visible')
      .getByDataTestid('menuMesProjetsBtn').click()
      .getByDataTestid('menuDashboard')
      .should('have.class', 'router-link-active')
  })
})
