describe('Sidebar', () => {
  it('Should display Sidebar, not loggedIn', () => {
    cy.visit('/')
      .getByDataTestid('mainMenu').should('be.visible')
      .getByDataTestid('menuProjectsList').should('not.exist')
      .getByDataTestid('menuProjectsBtn').should('not.exist')
      .getByDataTestid('menuDoc').click()
      .getByDataTestid('menuProjectsBtn').should('not.exist')
      .url().should('contain', '/doc')
      .getByDataTestid('menuDoc').should('have.class', 'router-link-active')
  })
  it('Should display Sidebar, loggedIn', () => {
    cy.kcLogin('test')
    cy.visit('/')
      .getByDataTestid('mainMenu').should('be.visible')
      .getByDataTestid('menuProjectsList').should('not.be.visible')
      .getByDataTestid('menuProjectsBtn').click()
      .getByDataTestid('menuProjectsList').should('be.visible')
      .getByDataTestid('menuDashboard').click()
      .url().should('contain', '/dashboard')
      .getByDataTestid('menuProjectsList').should('be.visible')
      .getByDataTestid('menuDoc').click()
      .getByDataTestid('menuProjectsList').should('not.be.visible')
      .url().should('contain', '/doc')
      .getByDataTestid('menuDoc').should('have.class', 'router-link-active')
  })
})
