import eslintConfigBase from '@cpn-console/eslint-config'

// Generated by `pnpm run swagger:generate` — never linted or hand-edited.
export default eslintConfigBase.append({ ignores: ['src/api/Api.ts'] })
