apiVersion: v1
kind: ResourceQuota
metadata:
  name: dso-quota
  namespace: {{ .Values.application.destination.namespace }}
  labels:
    app.kubernetes.io/managed-by: dso-console
    {{- .Values.commonLabels | toYaml | nindent 4 }}
spec:
  hard:
    limits.cpu: {{ .Values.application.quota.cpu | quote }}
    limits.memory: {{ .Values.application.quota.memory }}
    requests.cpu: {{ .Values.application.quota.cpu | quote }}
    requests.memory: {{ .Values.application.quota.memory }}

