---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443

service:
  type: NodePort
