imagePullPolicy: Always
env: production

imageCredentials:
  registry:
  username:
  password:
  email:

#hashmap of custom env applied on all pods
globalEnv:

containers:
  ansible:
    container:
      env: #hashmap of custom env
      image: ghcr.io/dnum-mi/dso-console/ansible:2
      playbooks:
        repoUrl: github.com/dnum-mi/dso-playbooks
        repoBranch: main
        # Use the 2 following if you want to clone a private repository
        repoUser:
        repoPass:
        repoMount: /dso/
        repoDir: /dso/
        # define where the inventory is in kube (see dso-infra repo, incoming)
        inventory:
          namespace: openshift-infra
          name: ansible-inventory
          key: inventory
      node_env: production
      port: 8080
    service:
      hostname: ansible
      port: 80

  server:
    container:
      env: #hashmap of custom env
      image: ghcr.io/dnum-mi/dso-console/server:2
      port: 8080
      node_env: production
      data-configmap: 
    service:
      port: 80
      hostname: server

  client:
    container:
      image: ghcr.io/dnum-mi/dso-console/client:2
      port: 8080
      env: #hashmap of custom env
    service:
      port: 80
      hostname: client
    route:
      host: replace.me

  postgres:
    container:
      env: #hashmap of custom env
      db: yourdbname
      user: youruser
      pass: yourpass
    service:
      hostname: postgres
      port: 5432

keycloak:
  domain:
  realm: yourkeycloakrealm
  admin:
  admin_password:
  client_id_frontend: console-frontend
  client_id_backend: console-backend
  client_secret_backend:
  redirect_uri:
  session_secret:

  container:
  # no deployment of keycloak just infos on how to connect other pods to it
  service:
    hostname:
    port:
