{{- if .Values.pgadmin.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        imagePullPolicy: IfNotPresent
        image: {{ .Values.pgadmin.container.image }}
        ports:
        - containerPort: {{ .Values.pgadmin.container.port }}
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@dso.fr
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        volumeMounts:
        - mountPath: /pgadmin4/servers.json
          name: pgadmin-config
      volumes:
      - name: pgadmin-config
        hostPath:
          path: /app/db/pgadmin/config/servers-kube.json
{{- end -}}
