{{- if .Values.keycloak.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        imagePullPolicy: IfNotPresent
        image: {{ .Values.keycloak.container.image }}
        command: {{ .Values.keycloak.container.command }}
        args: {{- toYaml .Values.keycloak.container.args | nindent 8 }}
        ports:
        - containerPort: {{ .Values.keycloak.container.port }}
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        volumeMounts:
        - mountPath: /opt/keycloak/data/import/realm-dev.json
          subPath: realm-dev.json
          name: realm-dev
      volumes:
      - name: realm-dev
        configMap:
          name: keycloak-realm
{{- end -}}
