{{- if .Values.postgres.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        imagePullPolicy: IfNotPresent
        image: {{ .Values.postgres.container.image }}
        ports:
        - containerPort: {{ .Values.postgres.container.port }}
        env:
        - name: POSTGRES_DB
          value: 
        - name: POSTGRES_USER
          value: 
        - name: POSTGRES_PASSWORD
          value: 
      #   volumeMounts:
      #   - mountPath: /pgadmin4/servers.json
      #     name: pgadmin-config
      # volumes:
      # - name: pgadmin-config
      #   hostPath:
      #     path: /app/db/pgadmin/config/servers.json
{{- end -}}
