{{- if .Values.keycloak.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.service.name }}
spec:
  selector:
    app: keycloak
  ports:
  - port: {{ .Values.keycloak.service.port }}
    targetPort: {{ .Values.keycloak.container.port }}
{{- end -}}
