{{- if .Values.pgadmin.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.service.name }}
spec:
  selector:
    app: pgadmin
  ports:
  - port: {{ .Values.pgadmin.service.port }}
    targetPort: {{ .Values.pgadmin.container.port }}
{{- end -}}
