global:
  env:
    NODE_ENV: "development"

server:
  image:
    repository: dso-console/server
    tag: dev
    pullPolicy: Never
  # startupProbe:
  #   enabled: false
  # readinessProbe:
  #   enabled: false
  # livenessProbe:
  #   enabled: false
  env:
    CI: "false"
    KEYCLOAK_DOMAIN: dso-cpn-keycloak
  extraVolumes:
    - name: dev-workspace
      path: /app/apps/server/src
      type: hostPath
    - name: dev-plugins
      path: /plugins
      type: hostPath
  extraVolumeMounts:
    - name: dev-workspace
      mountPath: /app/apps/server/src
    - name: dev-plugins
      mountPath: /plugins

client:
  image:
    repository: dso-console/client
    tag: dev
    pullPolicy: Never
  # startupProbe:
  #   enabled: false
  # readinessProbe:
  #   enabled: false
  # livenessProbe:
  #   enabled: false
  env:
    CI: "false"
  extraVolumes:
    - name: dev-workspace
      path: /app/apps/client/src
      type: hostPath
  extraVolumeMounts:
    - name: dev-workspace
      mountPath: /app/apps/client/src
