name: CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: "ghcr.io"
  NAMESPACE: "${{ github.repository }}"
  PLATFORM: "linux/amd64,linux/arm64"

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY: ${{ env.REGISTRY }}
      NAMESPACE: ${{ env.NAMESPACE }}
      PLATFORM: ${{ env.PLATFORM }}
    steps:
      - name: Exposing env vars
        run: echo "Exposing env vars"

  release:
    uses: ./.github/workflows/release.yml

  build:
    uses: ./.github/workflows/build.yml
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
      - expose-vars
      - release
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      PLATFORM: ${{ needs.expose-vars.outputs.PLATFORM }}
      TAG: ${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }},latest
