name: CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  NAMESPACE: "${{ github.repository }}"
  MULTI_ARCH: true
  USE_QEMU: false
  NODE_VERSION: 20.17.0
  PNPM_VERSION: 9.10.0

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY: ${{ env.REGISTRY }}
      NAMESPACE: ${{ env.NAMESPACE }}
      MULTI_ARCH: ${{ env.MULTI_ARCH }}
      USE_QEMU: ${{ env.USE_QEMU }}
      NODE_VERSION: ${{ env.NODE_VERSION }}
      PNPM_VERSION: ${{ env.PNPM_VERSION }}
    steps:
      - name: Exposing env vars
        run: echo "Exposing env vars"

  release:
    uses: ./.github/workflows/release.yml

  build:
    uses: ./.github/workflows/build.yml
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
      - expose-vars
      - release
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      TAG: ${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }}
      MAJOR_TAG: ${{ needs.release.outputs.major-tag }}
      MINOR_TAG: ${{ needs.release.outputs.minor-tag }}
      PATCH_TAG: ${{ needs.release.outputs.patch-tag }}
      MULTI_ARCH: ${{ needs.expose-vars.outputs.MULTI_ARCH == 'true' }}
      USE_QEMU: ${{ needs.expose-vars.outputs.USE_QEMU == 'true' }}

  npm-publish:
    uses: ./.github/workflows/npm.yml
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
      - expose-vars
      - release
    with:
      PNPM_VERSION: ${{ needs.expose-vars.outputs.PNPM_VERSION }}
      NODE_VERSION: ${{ needs.expose-vars.outputs.NODE_VERSION }}
      PUBLISH_APPS: false
      PUBLISH_PACKAGES: true
      PUBLISH_PLUGINS: true
      CHECK_CHANGES: false
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-chart:
    runs-on: ubuntu-latest
    needs:
      - expose-vars
      - release
      - build
    steps:
      - name: Trigger helm-charts update
        env:
          GH_TOKEN: ${{ secrets.HELM_CHART_TOKEN }}
        run: |
          gh workflow --repo cloud-pi-native/helm-charts run update-chart.yaml -f APP_VERSION=${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }} -f CHART_NAME=dso-console
