name: Playwright Tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      NODE_VERSION:
        description: Nodejs version used to run tests
        required: true
        type: string
      TAG:
        description: Container images version to use for console client and server/server-nestjs
        required: true
        type: string
        default: latest
jobs:
  test:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "${{ inputs.NODE_VERSION }}"

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache Node.js files
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: node-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            node-${{ runner.os }}-${{ runner.arch }}-

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Build internal dependencies
        run: pnpm --filter "./packages/**" build

      - name: Get used Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(pnpm --dir playwright exec playwright -V | awk '{ print $2 }')" >> $GITHUB_ENV

      - name: Restore cache - Playwright browser binaries
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright system dependencies
        run: pnpm --dir playwright exec playwright install --with-deps

      - name: Save cache - Playwright browser binaries
        if: always() && steps.playwright-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Initialize application environment for tests
        run: |
          ./ci/scripts/init-env.sh
          docker pull ghcr.io/cloud-pi-native/console/server:${{ inputs.TAG }}
          docker tag ghcr.io/cloud-pi-native/console/server:${{ inputs.TAG }} dso-console/server:ci
          docker pull ghcr.io/cloud-pi-native/console/nginx-strangler:${{ inputs.TAG }}
          docker tag ghcr.io/cloud-pi-native/console/nginx-strangler:${{ inputs.TAG }} dso-console/nginx-strangler:ci
          docker pull ghcr.io/cloud-pi-native/console/server-nestjs:${{ inputs.TAG }}
          docker tag ghcr.io/cloud-pi-native/console/server-nestjs:${{ inputs.TAG }} dso-console/server-nestjs:ci
          docker pull ghcr.io/cloud-pi-native/console/client:${{ inputs.TAG }}
          docker tag ghcr.io/cloud-pi-native/console/client:${{ inputs.TAG }} dso-console/client:ci
          docker buildx build -t dso-console/opencds-mockoon:ci packages/opencds/
          docker compose -f ./docker/docker-compose.ci.yml up --no-build -d --remove-orphans

      - name: Run Playwright tests
        run: pnpm --dir playwright exec playwright test --grep @e2e

      - name: Clean up docker resources (containers, volumes)
        run: docker compose -f ./docker/docker-compose.ci.yml down -v --remove-orphans

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
