name: Add labels on PR

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      CONF_PATH:
        required: true
        type: string

jobs:
  label:
    name: Add labels on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Add pull request label
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          configuration-path: ${{ inputs.CONF_PATH }}
