name: Publish npm

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      PUBLISH_APPS:
        required: true
        type: boolean
      PUBLISH_PACKAGES:
        required: true
        type: boolean
      PUBLISH_PLUGINS:
        required: true
        type: boolean
      CHECK_CHANGES:
        required: true
        type: boolean
  workflow_dispatch:
    inputs:
      NODE_VERSION:
        description: Nodejs version used
        required: true
        type: string
      PUBLISH_APPS:
        description: Publish apps modules
        required: true
        type: boolean
        default: false
      PUBLISH_PACKAGES:
        description: Publish packages modules
        required: true
        type: boolean
        default: false
      PUBLISH_PLUGINS:
        description: Publish plugins modules
        required: true
        type: boolean
        default: true
      CHECK_CHANGES:
        required: true
        type: boolean
        default: true

jobs:
  path-filter:
    if: ${{ inputs.CHECK_CHANGES }}
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Check updated files paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            eslint-config:
              - 'packages/eslintconfig/src/**'
            shared:
              - 'packages/shared/src/**'
            hooks:
              - 'packages/hooks/src/**'
            ts-config:
              - 'packages/tsconfig/**'
            logger:
              - 'packages/logger/**'
            argocd:
              - 'plugins/argocd/src/**'
            gitlab:
              - 'plugins/gitlab/src/**'
            harbor:
              - 'plugins/harbor/src/**'
            keycloak:
              - 'plugins/keycloak/src/**'
            nexus:
              - 'plugins/nexus/src/**'
            sonarqube:
              - 'plugins/sonarqube/src/**'
            vault:
              - 'plugins/vault/src/**'

  check-update:
    name: Check for package version update
    if: ${{ fromJson(needs.path-filter.outputs.packages).include[0] }} # skip if the matrix is empty!
    runs-on: ubuntu-latest
    needs:
      - path-filter
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.path-filter.outputs.packages) }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        id: pnpm-install
        with:
          run_install: false

      - name: Check changes
        id: check
        run: |
          PACKAGE_NAME=$(jq -cr --arg p "${{ matrix.packages }}" '[.packages[], .plugins[]][] | select(.name | test($p)?) | .name' < ./ci/matrix-npm.json)
          PACKAGE_PATH=$(jq -cr --arg p "${{ matrix.packages }}" '[.packages[], .plugins[]][] | select(.name | test($p)?) | .path' < ./ci/matrix-npm.json)
          PACKAGE_VERSION=$(jq -cr '.version' < ${PACKAGE_PATH}/package.json)
          if [ "$(curl -s -o /dev/null -I -w %{http_code} https://registry.npmjs.org/${PACKAGE_NAME})" = 404 ]; then
            REMOTE=false
          else
            REMOTE=$(pnpm view ${PACKAGE_NAME} --json | jq --arg v "$PACKAGE_VERSION" 'any(.versions[] == $v; .)')
          fi
          if [ "$REMOTE" = "true" ]; then
            echo "WARNING=true" >> $GITHUB_OUTPUT
            echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT
            echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_OUTPUT
            echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          else
            echo "WARNING=false" >> $GITHUB_OUTPUT
          fi

  matrix:
    name: Generate publish matrix
    needs:
      - path-filter
    if: ${{ needs.path-filter.outputs.packages != '' && (inputs.PUBLISH_APPS || inputs.PUBLISH_PACKAGES || inputs.PUBLISH_PLUGINS) }}
    runs-on: ubuntu-latest
    outputs:
      publish-matrix: ${{ steps.packages-matrix.outputs.PUBLISH_MATRIX }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Generate matrix
        id: packages-matrix
        run: |
          PUBLISH_MATRIX="[]"
          APPS_MATRIX="$(jq -c '.apps' < ./ci/matrix-npm.json)"
          PACKAGES_MATRIX="$(jq -c '.packages' < ./ci/matrix-npm.json)"
          PLUGINS_MATRIX="$(jq -c '.plugins' < ./ci/matrix-npm.json)"
          if [ "${{ inputs.PUBLISH_APPS }}" = "true" ]; then
            PUBLISH_MATRIX="$(jq -n -c --argjson acc "$PUBLISH_MATRIX" --argjson cur "$APPS_MATRIX" '$acc + $cur')"
          fi
          if [ "${{ inputs.PUBLISH_PACKAGES }}" = "true" ]; then
            PUBLISH_MATRIX="$(jq -n -c --argjson acc "$PUBLISH_MATRIX" --argjson cur "$PACKAGES_MATRIX" '$acc + $cur')"
          fi
          if [ "${{ inputs.PUBLISH_PLUGINS }}" = "true" ]; then
            PUBLISH_MATRIX="$(jq -n -c --argjson acc "$PUBLISH_MATRIX" --argjson cur "$PLUGINS_MATRIX" '$acc + $cur')"
          fi
          echo "PUBLISH_MATRIX=$PUBLISH_MATRIX" >> $GITHUB_OUTPUT

  publish-npm:
    name: Publish on npm
    if: ${{ needs.path-filter.outputs.packages != '' && (inputs.PUBLISH_APPS || inputs.PUBLISH_PACKAGES || inputs.PUBLISH_PLUGINS) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs:
      - path-filter
      - matrix
    strategy:
      # Allow jobs to be processed independently of their siblings status
      fail-fast: false
      matrix:
        modules: ${{ fromJSON(needs.matrix.outputs.publish-matrix) }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
        id: pnpm-install
        with:
          run_install: false

      - name: Check for new package version
        id: check-version
        run: |
          PACKAGE_VERSION=$(jq -cr '.version' < ${{ matrix.modules.path }}/package.json)
          if [ "$(curl -s -o /dev/null -I -w %{http_code} https://registry.npmjs.org/${{ matrix.modules.name }})" = 404 ]; then
            REMOTE=false
          else
            REMOTE=$(pnpm view ${{ matrix.modules.name }} --json | jq --arg v "$PACKAGE_VERSION" 'any(.versions[] == $v; .)')
          fi
          if [ "$REMOTE" = "true" ]; then
            echo "Package ${{ matrix.modules.name }} - version $PACKAGE_VERSION already exists"
          else
            echo "Package ${{ matrix.modules.name }} - version $PACKAGE_VERSION does not exist"
          fi
          echo "REMOTE=$REMOTE" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        with:
          node-version: "${{ inputs.NODE_VERSION }}"
          registry-url: "https://registry.npmjs.org"

      - name: Get pnpm store directory
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache node files
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: node-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            node-${{ runner.os }}-${{ runner.arch }}-

      - name: Install base dependencies
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        run: pnpm install --frozen-lockfile

      - name: Build internal dependencies
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        run: |
          pnpm --filter "./packages/**" run build && pnpm --filter "./plugins/**" run build

      - name: Update PNPM internal links with built internal dependencies
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        run: |
          pnpm install --frozen-lockfile

      - name: Build package
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        run: |
          pnpm --filter ${{ matrix.modules.name }} run build

      - name: Publish package
        if: ${{ steps.check-version.outputs.REMOTE == 'false' }}
        run: |
          pnpm --filter ${{ matrix.modules.name }} publish --provenance --no-git-checks --report-summary
