# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish npm

on:
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
        default: "20.10.0"
      MAJOR_TAG:
        type: string
        description: "Major version tag"
      MINOR_TAG:
        type: string
        description: "Minor version tag"
      PATCH_TAG:
        type: string
        description: "Patch version tag"
      PNPM_VERSION:
        description: Pnpm version used to run tests
        required: true
        type: string
        default: "8"
  workflow_dispatch:
    inputs:
      NODE_VERSION:
        required: true
        type: string
        default: "20.10.0"
      MAJOR_TAG:
        type: string
        description: "Major version tag"
      MINOR_TAG:
        type: string
        description: "Minor version tag"
      PATCH_TAG:
        type: string
        description: "Patch version tag"
      PNPM_VERSION:
        description: Pnpm version used to run tests
        required: true
        type: string
        default: "8"

jobs:
  publish-npm:
    name: Pubish on npm
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ inputs.NODE_VERSION }}"
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: "${{ inputs.PNPM_VERSION }}"
          run_install: true

      - name: Prepare packages
        run: |
          pnpm run db:generate
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' >> .npmrc

      - name: Publish on npmjs.org
        run: |
          pnpm publish --no-git-checks --access public \
            --filter server \
            --filter client \
            --filter shared
