name: Create new release PR

on:
  push:
    branches:
      - main

env:
  REGISTRY: "ghcr.io"

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      major-tag: ${{ steps.release.outputs.major }}
      minor-tag: ${{ steps.release.outputs.minor }}
      patch-tag: ${{ steps.release.outputs.patch }}
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Pre release new version
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: dso-console
          default-branch: main
          pull-request-title-pattern: v${version}
          token: ${{ secrets.GITHUB_TOKEN }}
