name: Tests - deploy

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string

jobs:
  deploy-check:
    name: Deploy check
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Run deployment status check
        run: |
          ./ci/scripts/init-env.sh
          ./ci/scripts/run-tests.sh -s -t "${{ inputs.TAG }}"
