name: Create/update next release

permissions:
  contents: write
  pull-requests: write
  # Needed for build job
  packages: write

on:
  push:
    branches:
      - main
      - hotfix/*

env:
  REGISTRY: ghcr.io
  NAMESPACE: "${{ github.repository }}"
  BUILD_AMD64: true
  BUILD_ARM64: true
  USE_QEMU: false
  NODE_VERSION: 24.13.1

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY: ${{ env.REGISTRY }}
      NAMESPACE: ${{ env.NAMESPACE }}
      BUILD_AMD64: ${{ env.BUILD_AMD64 }}
      BUILD_ARM64: ${{ env.BUILD_ARM64 }}
      USE_QEMU: ${{ env.USE_QEMU }}
      NODE_VERSION: ${{ env.NODE_VERSION }}
    steps:
      - name: Exposing env vars
        run: echo "Exposing env vars"

  release:
    uses: ./.github/workflows/job-release-please.yml

  build-amd64:
    uses: ./.github/workflows/job-build.yml
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
      - expose-vars
      - release
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      TAG: ${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }}
      MAJOR_TAG: ${{ needs.release.outputs.major-tag }}
      MINOR_TAG: ${{ needs.release.outputs.minor-tag }}
      PATCH_TAG: ${{ needs.release.outputs.patch-tag }}
      BUILD_AMD64: ${{ needs.expose-vars.outputs.BUILD_AMD64 == 'true' }}
      BUILD_ARM64: false
      USE_QEMU: ${{ needs.expose-vars.outputs.USE_QEMU == 'true' }}
      SKIP_MERGE: true

  build-arm64:
    uses: ./.github/workflows/job-build.yml
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
      - expose-vars
      - release
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      TAG: ${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }}
      MAJOR_TAG: ${{ needs.release.outputs.major-tag }}
      MINOR_TAG: ${{ needs.release.outputs.minor-tag }}
      PATCH_TAG: ${{ needs.release.outputs.patch-tag }}
      BUILD_AMD64: false
      BUILD_ARM64: ${{ needs.expose-vars.outputs.BUILD_ARM64 == 'true' }}
      USE_QEMU: ${{ needs.expose-vars.outputs.USE_QEMU == 'true' }}
      SKIP_MERGE: true

  merge-manifests:
    name: Merge digest
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release-created == 'true' }}
    needs:
      - expose-vars
      - release
      - build-amd64
      - build-arm64
    steps:
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          pattern: digests-*.*.digest
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: ${{ needs.expose-vars.outputs.REGISTRY }}/${{ needs.expose-vars.outputs.NAMESPACE }}/server
          tags: |
            type=raw,value=${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }}
            type=raw,value=${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}
            type=raw,value=${{ needs.release.outputs.major-tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ needs.expose-vars.outputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ needs.expose-vars.outputs.REGISTRY }}/${{ needs.expose-vars.outputs.NAMESPACE }}/server@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ needs.expose-vars.outputs.REGISTRY }}/${{ needs.expose-vars.outputs.NAMESPACE }}/server:${{ steps.meta.outputs.version }}

  update-chart:
    runs-on: ubuntu-latest
    needs:
      - expose-vars
      - release
      - build-amd64
      - build-arm64
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: helm-charts
      - name: Trigger helm-charts update
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh workflow --repo cloud-pi-native/helm-charts run update-chart.yaml -f APP_VERSION=${{ needs.release.outputs.major-tag }}.${{ needs.release.outputs.minor-tag }}.${{ needs.release.outputs.patch-tag }} -f CHART_NAME=dso-console
