name: Build and deploy latest from main

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  NAMESPACE: "${{ github.repository }}"
  BUILD_AMD64: true
  USE_QEMU: false
  NODE_VERSION: 26.7.0

jobs:
  expose-vars:
    runs-on: ubuntu-latest
    outputs:
      REGISTRY: ${{ env.REGISTRY }}
      NAMESPACE: ${{ env.NAMESPACE }}
      BUILD_AMD64: ${{ env.BUILD_AMD64 }}
      USE_QEMU: ${{ env.USE_QEMU }}
      NODE_VERSION: ${{ env.NODE_VERSION }}
    steps:
      - name: Exposing env vars
        run: echo "Exposing env vars"

  build-amd64:
    uses: ./.github/workflows/job-build.yml
    needs:
      - expose-vars
    with:
      REGISTRY: ${{ needs.expose-vars.outputs.REGISTRY }}
      NAMESPACE: ${{ needs.expose-vars.outputs.NAMESPACE }}
      RELEASE_CREATED: false
      TAG: ''
      MAJOR_TAG: ''
      MINOR_TAG: ''
      PATCH_TAG: ''
      BUILD_AMD64: ${{ needs.expose-vars.outputs.BUILD_AMD64 == 'true' }}
      BUILD_ARM64: false
      USE_QEMU: ${{ needs.expose-vars.outputs.USE_QEMU == 'true' }}
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
