integration: false

kubeconfig: ""

data: ""

pgadmin:
  enabled: true
  container:
    image: docker.io/dpage/pgadmin4:8.5
    port: 80
  service:
    name: pgadmin-service
    port: 80
    type: ClusterIP
  ingress:
    host: pgadmin.dso.local

keycloak:
  enabled: true
